### ISSUE TITLE
Incorrectly formatted JSON for Windows 10 MDM Policies

### ISSUE THREAD

**Issue by embrionic-mike** [ukncsc/Device-Security-Guidance-Configuration-Packs#1]
The Windows 10 MDM Policies for AppLocker, Internet Explorer and Chrome do not import as the JSON in the policies is incorrectly formatted. The files are missing the Windows 10 Custom Configuration parent for the OMA settings and therefore fail to import with the error: 

Response content:
{"error":{"code":"ModelValidationFailure","message":"Cannot create an abstract class.","innerError":{"message":"Cannot create an abstract class.","date":"2021-06-30T10:55:32","request-id":"2aff32fb-02a0-40cb-831f-3964852057cd","client-request-id":"2aff32fb-02a0-40cb-831f-3964852057cd"}}}
Add-DeviceConfigurationPolicy : Request to https://graph.microsoft.com/v1.0/deviceManagement/deviceConfigurations
failed with HTTP Status BadRequest Bad Request
At C:\Users\SomeUser\SomePath
\Intune\DeviceConfiguration_Import_FromJSON.ps1:343 char:1
+ Add-DeviceConfigurationPolicy -JSON $JSON_Output
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-DeviceConfigurationPolicy

The JSON should follow the guidance in https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-windows10customconfiguration-create?view=graph-rest-1.0.

**Comment by AdamF1** [comment]
Hey, thanks for reporting this! This is now fixed in https://github.com/ukncsc/Device-Security-Guidance-Configuration-Packs/commit/fe41c30354e72e9f7931163898568fd0ce610ea3 and will be included in a new release shortly
