### ISSUE TITLE
[CHANGE CONFIGURATION] ineffective sed commands (checking before submitting PR)

### ISSUE THREAD

**Issue by mokytis** [ukncsc/Device-Security-Guidance-Configuration-Packs#11]
**Which platform does your requested change effect?**
Linux/UbuntuLTS

**Is your feature request related to a problem? Please describe.**

There are several sed commands such as `sed '/APT::Periodic::Unattended-Upgrade/d' /etc/apt/apt.conf.d/20auto-upgrades` that have no real effect on the file, but just output a manipulation of the file to stdout.

As you can see here the content isn't modified

```
$ cat testfile
this is
a test
file
it contains
some
file
contents

$ sed '/file/d' testfile
this is
a test
it contains
some
contents

$ cat testfile
this is
a test
file
it contains
some
file
contents
```

but if I add `-i` it is

```
$ sed -i '/file/d' testfile

$ cat testfile
this is
a test
it contains
some
contents
```
I believe that this is stopping these sed commands from having the desired effect, although I may be misunderstanding their purpose.

I am happy to submit a PR fixing all instances of this if you also view it as a probelm.

**Comment by AdamF1** [comment]
Thanks for this, we will investigate it and get back to you

**Comment by AdamF1** [comment]
Hi, we've have looked and fixed the error you mentioned in https://github.com/ukncsc/Device-Security-Guidance-Configuration-Packs/commit/1f4f8eca928fdfcbe7c09d4c5300179f2576e093. 
It was working as it was written but thank you for flagging it as it could have caused problems later down the line.
