### ISSUE TITLE
Firewall and rules configs

### ISSUE THREAD

**Issue by jlb67** [ukncsc/Device-Security-Guidance-Configuration-Packs#2]
Hi,

although the json file appears in the configuration area within intune the properties are empty for both the firewall and rules.

!
![ncsc-firewall](https://user-images.githubusercontent.com/54314213/124105149-d4fa0900-da5a-11eb-99f4-819722ac71f2.png)

thanks

**Comment by AdamF1** [comment]
Thank you for raising this! Documentation has been included to explain their presence https://github.com/ukncsc/Device-Security-Guidance-Configuration-Packs/commit/cdbfc91354549ce6140b632faa19fc939c8ad0b1
