### ISSUE TITLE
[CHANGE CONFIGURATION] - Device Restriction profiles conflict around blocking DMA access

### ISSUE THREAD

**Issue by MatthewWhiteMoJ** [ukncsc/Device-Security-Guidance-Configuration-Packs#4]
**Which platform does your requested change effect?**
Windows 10

**Which configuration setting are you requesting change to?**
All Device Restriction profiles

**What is the current value for that configuration and what are you suggesting it be changed to?**
There is a conflict after policies are uploaded. By default the DMA Access is set to Enabled in all Device Restriction profiles when it is not configured. This causes conflict with other profiles.

**Is your feature request related to a problem? Please describe.**
Simply uploading the profiles and applying to devices will leave the devices with Conflict and likely result of blocking DMA access is not achieved

**How does the requested change fit within the [guiding principles](https://github.com/ukncsc/Device-Security-Guidance-Configuration-Packs#guiding-principles)?**

Change should ensure that future users can upload the json templates and not have any conflicts

**Comment by danu-ncsc** [comment]
Thanks for reporting this - we'll look into this within the next two weeks.

**Comment by AdamF1** [comment]
Thank you, amended configurations to have consistent DMA setting. https://github.com/ukncsc/Device-Security-Guidance-Configuration-Packs/commit/7f2eaa01429c9ff40071c3dd9901ee7f3f82242b
