### ISSUE TITLE
Applocker DLL Missing Teams addin

### ISSUE THREAD

**Issue by andyunder** [ukncsc/Device-Security-Guidance-Configuration-Packs#5]
The Teams Outlook add-in DLL is missing from the AppLocker DLL xml.

Could this be added to future builds

**Comment by andyunder** [comment]
While looking at this could you please look at PowerShell as you can run PowerShell but not PowerShell ISE

**Comment by AdamF1** [comment]
In relation to the Teams Outlook add-in, can you specify the name of the DLL and any Microsoft documentation relating to it? We are open to including it, but we'd need evidence of usage in either large UK businesses or a UK government department to justify inclusion at this stage.

In relation to the PowerShell query, the wish was to restrict script usage, so the ISE was added into AppLocker but PowerShell itself was left available. These are guidelines so you can add or remove items as you require for your specific needs.

**Comment by andyunder** [comment]
The full location of the DLL is "C:\Users\%username%\AppData\Local\Microsoft\TeamsMeetingAddin\*\x64\Microsoft.Teams.AddinLoader.dll"

As this is a standard DLL for teams and creating meetings direct from outlook this is likely to be used by all sizes of organisation.
This link is to using the teams add in in outlook
https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook

With regards to ISE would this not make more sense be to the other way round due to scripts being ran in PowerShell but written in ISE or be blocking both
